"""add vibe columns

Revision ID: 03218d60ac4d
Revises: ac365dce23e2
Create Date: 2026-10-07 21:25:26.463005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03218d60ac4d'
down_revision: Union[str, Sequence[str], None] = 'ac365dce23e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('honeybee_memories_hnsw_idx'), table_name='honeybee_memories', postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('honeybee_memories_text_lemmatized_idx'), table_name='honeybee_memories', postgresql_using='gin')
    op.drop_table('honeybee_memories')
    op.drop_index(op.f('honeybee_docs_hnsw_idx'), table_name='honeybee_docs', postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('honeybee_docs_text_lemmatized_idx'), table_name='honeybee_docs', postgresql_using='gin')
    op.drop_table('honeybee_docs')
    op.add_column('users', sa.Column('vibe_prompt', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('vibe_examples', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vibe_examples')
    op.drop_column('users', 'vibe_prompt')
    op.create_table('honeybee_docs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('honeybee_docs_pkey'))
    )
    op.create_index(op.f('honeybee_docs_text_lemmatized_idx'), 'honeybee_docs', [sa.literal_column("to_tsvector('simple'::regconfig, payload ->> 'text_lemmatized'::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('honeybee_docs_hnsw_idx'), 'honeybee_docs', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_table('honeybee_memories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('honeybee_memories_pkey'))
    )
    op.create_index(op.f('honeybee_memories_text_lemmatized_idx'), 'honeybee_memories', [sa.literal_column("to_tsvector('simple'::regconfig, payload ->> 'text_lemmatized'::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('honeybee_memories_hnsw_idx'), 'honeybee_memories', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
