"""remove vibe examples column

Revision ID: 5282dcb663d4
Revises: 03218d60ac4d
Create Date: 2026-10-07 21:32:30.868731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5282dcb663d4'
down_revision: Union[str, Sequence[str], None] = '03218d60ac4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vibe_examples')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vibe_examples', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
